# Generated by Django 5.2.12 on 2026-03-20 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('correction_type', models.CharField(choices=[('premium', 'Premium'), ('standard', 'Standard')], max_length=20)),
                ('turnaround_hours', models.IntegerField(default=72)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
