# Generated by Django 4.2.7 on 2026-04-22 15:51

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['price'], 'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
        migrations.AddField(
            model_name='service',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Creation Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Updated'),
        ),
        migrations.AlterField(
            model_name='service',
            name='correction_type',
            field=models.CharField(choices=[('standard', 'Standard'), ('premium', 'Premium')], default='standard', help_text='Type of service: Standard (free) or Premium (paid)', max_length=20, verbose_name='Correction Type'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed description of the service', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='service',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Is the service available?', verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(help_text='Name of the correction service', max_length=100, verbose_name='Service Name'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Price of the service in dollars ($)', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='service',
            name='turnaround_hours',
            field=models.IntegerField(default=72, help_text='Correction turnaround time in hours', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Turnaround (hours)'),
        ),
    ]
