# Generated by Django 5.2.12 on 2026-05-11 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('CORRECTED', 'Corrected')], default='PENDING', max_length=20),
        ),
    ]
