# Generated by Django 5.2.12 on 2026-05-18 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_alter_assignment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('stripe', 'Card (Stripe)'), ('cash', 'Cash on Delivery')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='payment_status',
            field=models.CharField(choices=[('UNPAID', 'Unpaid'), ('PAID', 'Paid'), ('PENDING_CASH', 'Cash Pending')], default='UNPAID', max_length=15),
        ),
        migrations.AddField(
            model_name='assignment',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
