# Generated by Django 5.2.12 on 2026-05-11 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corrections', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='correction',
            old_name='comment',
            new_name='comments',
        ),
        migrations.AddField(
            model_name='correction',
            name='suggestions',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='correction',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20),
        ),
    ]
