# Generated by Django 5.2.12 on 2026-05-11 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('TUTOR', 'Tutor'), ('ADMIN', 'Administrator')], default='STUDENT', max_length=20),
        ),
    ]
